### ISSUE TITLE
keycloak's app server does not reject TLS1.0, 1.1, insecure cipher suites defined in FAPI-RW-8.5-2

### ISSUE THREAD

**Issue by tnorimat** [jsoss-sig/keycloak-fapi#18]
To pass these tests, the keycloak's application server (wildfly) accept only TLSv1.2 and cipher suites defined in FAPI-RW-8.5-2 in Handshake, and reject others.

The following might be helpful :

* https://www.keycloak.org/docs/latest/server_admin/index.html#_enable-mtls-wildfly

* https://docs.jboss.org/author/display/WFLY10/Undertow+subsystem+configuration
 HTTPS Listener - enabled-cipher-suites

* https://stackoverflow.com/questions/33684451/wildfly-ssl-protocol-tlsv1-2-configuration

**Comment by wadahiro** [comment]
TLS 1.0 and 1.1 are rejected in the pull request: https://github.com/jsoss-sig/keycloak-fapi/pull/29

![image](https://user-images.githubusercontent.com/28739/83145392-add25900-a12f-11ea-86bc-4c87ba37016c.png)

I'll try to setup keycloak (WildFly) to reject insecure cipher suite (`TLS_RSA_WITH_AES_256_GCM_SHA384`).

**Comment by wadahiro** [comment]
Fixed in https://github.com/jsoss-sig/keycloak-fapi/pull/29. I added a configuration into WildFly in https://github.com/jsoss-sig/keycloak-fapi/pull/29/commits/42205bafa3935c2dcb95d1ee807b33f920cfb783.

![image](https://user-images.githubusercontent.com/28739/83163219-c2215080-a145-11ea-9937-a4a07a8fb54d.png)

@tnorimat Now, we can close this issue.

**Comment by tnorimat** [comment]
@wadahiro Thank you! I'll close this issue.
