### ISSUE TITLE
FAPI-RW-8.5-2: DisallowTLS10, DisallowTLS11, DisallowInsecureCipher

### ISSUE THREAD

**Issue by wadahiro** [jsoss-sig/keycloak-fapi#5]
The server accepted a TLS 1.0 and 1.1 connection. This is not permitted by the specification. Also, the server accepted a disallowed cipher: `TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256`.

https://openid.net/specs/openid-financial-api-part-2-ID2.html#tls-considerations

**Comment by tnorimat** [comment]
It seems that these tests are for the resource server, not the authorization server (keycloak). To pass these tests, the application server defined as "resourceUrl" in the config file needs to be configured to accept only TLSv1.2 and cipher suites defined in FAPI-RW-8.5-2 in Handshake, and reject others.

These test should be omitted because the test plan is for the authorization server (keycloak), not the resource server.

**Comment by wadahiro** [comment]
Fixed in https://github.com/jsoss-sig/keycloak-fapi/commit/4e8acac4928c531638f3998723778605a0142d73.

I confirmed FAPI-RW-8.5-2 was passed:

![image](https://user-images.githubusercontent.com/28739/82966672-5ab0b700-a006-11ea-8bd2-932a08928779.png)

**Comment by tnorimat** [comment]
@wadahiro Thank you. I'll close this issue.
