### ISSUE TITLE
Resource Server related FAILURE : x-fapi-interaction-id

### ISSUE THREAD

**Issue by tnorimat** [jsoss-sig/keycloak-fapi#7]
CheckForFAPIInteractionIdInResourceResponse and EnsureMatchingFAPIInteractionId checks x-fapi-interaction-id (FAPI-R-6.2.1-11, 12) in HTTP response header from Resource Server. 

To pass these tests, the resource server defined as "resourceUrl" in the config file needs to be configured to satisfy x-fapi-interaction-id related requirements (FAPI-R-6.2.1-11, 12).

These test should be omitted because the test plan is for the authorization server (keycloak), not the resource server.

**Comment by wadahiro** [comment]
Fixed in https://github.com/jsoss-sig/keycloak-fapi/commit/c92a6265eff4edf575b6d080b7240e42f46341b4#diff-d8030dde0c7f87e12e501ba4fb152a3c temporarily.
To pass the test, it uses customized keycloak-gatekeeper to support `x-fapi-interaction-id` header which was added in the following commit:

https://github.com/openstandia/keycloak-gatekeeper/commit/af4198d674dc540771eb041390f19c644c0deae7

**Comment by tnorimat** [comment]
@wadahiro Thank you. This issue will  be closed.
